### ISSUE TITLE
Remove --readonly and (READONLY)

### ISSUE THREAD

**Issue by MaskRay** [systemd/package-notes#28]
`(READONLY)` was added to remove SHF_WRITE from the `.note.package` sh_flags. However, an output section defaults to not have SHF_WRITE after the GNU ld fix (https://sourceware.org/bugzilla/show_bug.cgi?id=26378#c11). For ld.lld, it does not use SHF_WRITE from the beginning.

See

* https://sourceware.org/pipermail/binutils/2022-January/119537.html
* https://sourceware.org/pipermail/binutils/2022-February/119627.html

**Comment by bluca** [comment]
NACK, this is required

**Comment by MaskRay** [comment]
If you have an example `.note.package` has the SHF_WRITE flag, please mention it and hopefully other contributors can identify or fix the problem. If it is a GNU ld bug, let Alan Modra/Nick Clifton know and hopefully they will fix it (given the direction of https://sourceware.org/bugzilla/show_bug.cgi?id=26378#c11)).

**Comment by bluca** [comment]
There is nothing to fix, it is all working as intended, please stop creating entropy
