### ISSUE TITLE
package notes removed from lld, but is supported since 16.0.0

### ISSUE THREAD

**Issue by grooverdan** [systemd/package-notes#44]
lld added package-metadata in https://github.com/llvm/llvm-project/commit/dbd04b853b680b0a383e5f58edf3643364f67bdf

so can be removed from, or have version related test in, debian-package-notes.specs and macros.package-notes-srpm

**Comment by bluca** [comment]
You can use it manually, but llvm doesn't support compiler spec files or similar mechanisms, so it cannot be used in packages

**Comment by grooverdan** [comment]
Ah, I see. Thanks.
